server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token



#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#
#  这句的作用是： 开启数据库字段名和 Java 属性名之间的驼峰映射 。什么意思？ 比如数据库列名可能是： create_time update_time id_number。
#  而 Java Employee 类里一般会写成：createTime updateTime idNumber。开启这个配置后，MyBatis 会自动帮你对应上。
#  所以数据库结果才能顺利装进 Employee 对象。这也是 Mapper 能返回 Employee 的底层细节之一